### ISSUE TITLE
Downloading jboss logging jar for keycloak login module support 

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/arkmq-org-broker-init-image#30]
**Describe the bug**
As the new broker distribution migrated its logging from jboss logging to slf4j/log4j 2, the jboss logging jars are not shipped.
However the keycloak client(12.0.3) still depends on jboss-logging. The init container should added those jars in case the keycloak login module is configured.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Container build tool [e.g. Podman]

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
@gaohoward the last activemq-artemis-broker-kubernetes-image already includes all the required keycloak deps. Maybe the `CopyKeycloakDependencies` function could be removed, for further details see https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/issues/48, WDYT?

**Comment by tlbueno** [comment]
@gaohoward  based on @brusdev comment above I think this one should be closed. Do you agree?

**Comment by tlbueno** [comment]
After discussing it with @gaohoward we agreed that it can be closed.
